CREATE TABLE movie_rating (
    id BIGINT NOT NULL AUTO_INCREMENT,
    watch_entry_id BIGINT NOT NULL,
    story_screenplay DECIMAL(2, 1) NOT NULL,
    direction DECIMAL(2, 1) NOT NULL,
    performances_characters DECIMAL(2, 1) NOT NULL,
    pacing_editing DECIMAL(2, 1) NOT NULL,
    visuals_art_design DECIMAL(2, 1) NOT NULL,
    music_sound DECIMAL(2, 1) NOT NULL,
    themes_depth DECIMAL(2, 1) NOT NULL,
    originality_concept DECIMAL(2, 1) NOT NULL,
    personal_impact_enjoyment DECIMAL(2, 1) NOT NULL,
    technical_score DECIMAL(4, 2) NOT NULL,
    objective_score DECIMAL(4, 2) NOT NULL,
    display_score DECIMAL(2, 1) NOT NULL,
    personal_final_score DECIMAL(2, 1) NULL,
    review_summary TEXT NULL,
    private_notes TEXT NULL,
    category_notes_json TEXT NULL,
    rating_profile_version INT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    CONSTRAINT pk_movie_rating PRIMARY KEY (id),
    CONSTRAINT uk_movie_rating_watch_entry_id UNIQUE (watch_entry_id),
    CONSTRAINT fk_movie_rating_watch_entry FOREIGN KEY (watch_entry_id) REFERENCES watch_entry (id) ON DELETE CASCADE,
    CONSTRAINT fk_movie_rating_profile_version FOREIGN KEY (rating_profile_version) REFERENCES rating_profile (version),
    CONSTRAINT ck_movie_rating_story_screenplay CHECK (story_screenplay BETWEEN 0.0 AND 5.0 AND MOD(story_screenplay * 10, 5) = 0),
    CONSTRAINT ck_movie_rating_direction CHECK (direction BETWEEN 0.0 AND 5.0 AND MOD(direction * 10, 5) = 0),
    CONSTRAINT ck_movie_rating_performances CHECK (performances_characters BETWEEN 0.0 AND 5.0 AND MOD(performances_characters * 10, 5) = 0),
    CONSTRAINT ck_movie_rating_pacing CHECK (pacing_editing BETWEEN 0.0 AND 5.0 AND MOD(pacing_editing * 10, 5) = 0),
    CONSTRAINT ck_movie_rating_visuals CHECK (visuals_art_design BETWEEN 0.0 AND 5.0 AND MOD(visuals_art_design * 10, 5) = 0),
    CONSTRAINT ck_movie_rating_music CHECK (music_sound BETWEEN 0.0 AND 5.0 AND MOD(music_sound * 10, 5) = 0),
    CONSTRAINT ck_movie_rating_themes CHECK (themes_depth BETWEEN 0.0 AND 5.0 AND MOD(themes_depth * 10, 5) = 0),
    CONSTRAINT ck_movie_rating_originality CHECK (originality_concept BETWEEN 0.0 AND 5.0 AND MOD(originality_concept * 10, 5) = 0),
    CONSTRAINT ck_movie_rating_personal_impact CHECK (personal_impact_enjoyment BETWEEN 0.0 AND 5.0 AND MOD(personal_impact_enjoyment * 10, 5) = 0),
    CONSTRAINT ck_movie_rating_technical_score CHECK (technical_score BETWEEN 0.0 AND 5.0),
    CONSTRAINT ck_movie_rating_objective_score CHECK (objective_score BETWEEN 0.0 AND 5.0),
    CONSTRAINT ck_movie_rating_display_score CHECK (display_score BETWEEN 0.0 AND 5.0 AND MOD(display_score * 10, 5) = 0),
    CONSTRAINT ck_movie_rating_personal_final_score CHECK (personal_final_score IS NULL OR (personal_final_score BETWEEN 0.0 AND 5.0 AND MOD(personal_final_score * 10, 5) = 0))
);
