spring:
  datasource:
    url: jdbc:h2:mem:cinelog;MODE=MariaDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  flyway:
    enabled: true

cinelog:
  security:
    remember-me-key: test-only-remember-me-key
